sudo: required

services:
- docker

language: node_js
node_js:
- node

script:
- docker build . -t foobert/jwtdummy
- bin/test.sh

deploy:
  provider: script
  script: bash bin/push.sh
  on:
    all_branches: true
